### ISSUE TITLE
Erstellen eines Groben Planes  des Banksystems 

### ISSUE THREAD

**Issue by Marckfx** [Smart-City-SoSe-2022/Banksystem#1]
- [ ] UML
- [ ] Grobes System Aufschreiben 
- [ ]  ER-Model
- [ ] API Aufrufe entwickeln
- [ ]  Ablaufplan 
- [ ] Anforderungen und Entwurfs Spezifikation ausarbeiten
